### ISSUE TITLE
Add new standard habit 

### ISSUE THREAD

**Issue by SashaKarpova** [ita-social-projects/GreenCity#1000]
**As a registered User, I want to be able to add new habit from the standard habits in the system.** 

Registered User should be able to add a new habit from the standard habits in the system.
User should be able to invite other users to acquire the habit.

Acceptance Criteria:
1. If user has less than 6 habits in progress and clicks the ‘Add new habits’ button, he redirect on page ‘Add new habits’ where he could select and add habit. 
2. ‘Add new habits’ page has drop-down list with defaults habits, box ‘Day’, buttons ‘Save’ and ‘Cancel’, check-box ‘Create custom habit’.
3. When User selects habit from drop-down list, amount of days display on box ‘Day’.
4. When Logged User selects habit and clicks the ‘Save’ button: the system adds the new habit and redirect on ‘My habits’ page.
5. New habit is displayed in the top on ‘My habits page’
6. When Logged User clicks the ‘Cancel’ button: the system didn’t add new habit and redirect on ‘My habits’ page.
7. If user has 6 habits in progress and clicks the ‘Add new habits’ button, system opens pop-up with information:  user to be able to have only 6 habits in progresses.

**Draft mockup ‘Add new habits’ page**
![draft mockup copy copy](https://user-images.githubusercontent.com/65449340/88515914-1d13de80-cff5-11ea-8c7c-6653f17e2c2e.jpg)

**Table with default habits**
[standard  system habits.xlsx](https://github.com/ita-social-projects/GreenCity/files/4980638/standard.system.habits.xlsx)

**Comment by Mariana-Khishchenko** [comment]
**Title:**
Add new standard Habit (My habit list)
**Description:**
As a registered user, I  want to be able to add new habit from a list of standard habits, so that I was able to track the progress of each specific habit
**Assumptions & Constrains:**
•	List of standards habit exist in the system
**Preconditions:**
•	Registered User logged in  
•	My habits page is open
**Business rules:**
1 registered user can have only 6 Active ‘In Process’ Habits
**Acceptance Criteria:**
1. Registered User can see the enabled “Add New Habit” button on the “My Habit” page 
![image](https://user-images.githubusercontent.com/73824853/97857632-b9d9cc80-1d06-11eb-842a-1066042f917e.png)

2. When reg. User clicks the “Add New Habit” button, the system redirects him to the All Habits list page
        a. User is able to scroll and review all standard habits. 
        b. When User Clicks ‘Back to My Habits’ system redirects him to My Habits tab in the profile
        c. Buttons Add Habit and More are enabled.
![image](https://user-images.githubusercontent.com/73824853/97857851-fdccd180-1d06-11eb-9d64-ec25cd6d11b7.png)

3. User adds one standard habit to ‘My Habits’ list by clicking  ‘Add Habit’ button
4. System redirects User to the ‘My habit’ page. Newly added habits must be displayed on the top of all habits list. The system opens a pop-up with information: “You have successfully added a new habit to your list” (green error)
![image](https://user-images.githubusercontent.com/73824853/97857236-1983a800-1d06-11eb-8353-c3ece395979b.png)

5. If the user has 6 habits in progress and clicks the ‘Add new habits’ button, the system opens a pop-up with information: “Users can have only 6 habits In Progress” (yellow error)
![image](https://user-images.githubusercontent.com/73824853/97857318-33bd8600-1d06-11eb-9491-988b13523fa2.png)
