### ISSUE TITLE
[Enroll habit for a specific day]Habit Status Controller returns status 400 when enroll and unenroll are called

### ISSUE THREAD

**Issue by forestik** [ita-social-projects/GreenCity#1632]
**Environment:** Windows 10 Home, Google Chrome
**Reproducible:** always.

**Steps to reproduce**
1. Go to 'https://greencity.azurewebsites.net/swagger-ui.html#/habit-status-controller/unenrollHabitUsingPOST' or 'https://greencity.azurewebsites.net/swagger-ui.html#/habit-status-controller/enrollHabitInDateUsingPOST'
2. Set habitAssignId 1
3. Execute request.

There is no field to set the value for the **date** field.

**Actual result**
Response 400:
{
  "message": "Wrong date. Should be 'LocalDate'"
}

**Expected result**
Response 200 Ok

**Comment by oprotyniak** [comment]
Enroll doesn't have "Date" field. Unenroll has same actual result when date is e.g. '02.12.2020'. If date is '02/12/2020' actual result is:
![image](https://user-images.githubusercontent.com/73852063/100927753-fd824a80-34ed-11eb-9ce4-0e9db2aff890.png)

I changed HabitID from '1' to '5', because for '1' I have this result:
![image](https://user-images.githubusercontent.com/73852063/100927905-302c4300-34ee-11eb-89b4-314ff1285edd.png)
