### ISSUE TITLE
[my habits] Shopping list does not shown

### ISSUE THREAD

**Issue by ViktoriyaRyazhska** [ita-social-projects/GreenCity#2206]
**Environment:** All browsers
**Reproducible:** always
**Build found:** 22.01.21

**Preconditions**
1. App is opened https://ita-social-projects.github.io/GreenCityClient/#/
2. User is logged
3. User has at least one active habit

**Steps to reproduce**
1. Go to 'My habits' page
2. Click on 'Edit Profile' button
3. Select 'Show my shopping list' checkbox
4. Click on 'Save' button

**Actual result**
Loader is displayed on right panel on 'Habit' page

**Expected result**
'Shopping list' section with correspond items is displayed on right panel on 'Habit' page

**User story and test case links**
User story #100
[Test case](https://jira.softserve.academy/browse/100)"

**Labels to be added**
"Bug", Priority ("pri: "), Severity ("severity:"), Type ("UI, "Functional"), "API" (for back-end bugs).

**Comment by IrynaMarkovych** [comment]
<img width="1215" alt="Screen Shot 2021-03-09 at 8 46 47 PM" src="https://user-images.githubusercontent.com/79633583/110522478-9d68f900-8119-11eb-85c8-7fa38ef795c8.png">
The issue is still reproducible:

1. Loader is displayed on left panel on 'Habit' page
2. The 'You don't have authorities' pop-up appears
