### ISSUE TITLE
[UBS Admin Certificates] Change size and positions of buttons

### ISSUE THREAD

**Issue by Yura935** [ita-social-projects/GreenCity#3503]
Size of buttons "Експортувати в Excel" та "Додати сертифікат" is incorrect.

**Comment by MyroslavaVynokur** [comment]
The width of "Експортувати в Excel" button should be 190 px according to new figma instead of 210 px:
https://www.figma.com/file/JvDAu4MHnh1Vxc5FaokyiA/ITA-UBS-styles?node-id=15642%3A91995

Also please have a look to edit pictogram on "Вид таблиці" button, here is actual pictogram:
<img width="134" alt="Screenshot 2021-11-26 at 16 51 33" src="https://user-images.githubusercontent.com/34717146/143598511-5a0c140f-b301-4b1f-9c24-3bd89e04b6e3.png">

Should be this one:
<img width="271" alt="Screenshot 2021-11-26 at 16 52 31" src="https://user-images.githubusercontent.com/34717146/143598594-685a7c7d-fcd8-45c8-b997-4e5006cc4e34.png">
