### ISSUE TITLE
[Admin. Orders] Missing of status "Оплачено" for filtering "Статус замовлення", wrong order of statuses

### ISSUE THREAD

**Issue by Olya-Kashchin** [ita-social-projects/GreenCity#4255]
**Environment:** macOS Monterey Version 12.3.1, Chrome 101.0.4951.54
**Reproducible:** always
**Build found:** 31.05.2022

**Preconditions**
Go to https://ita-social-projects.github.io/GreenCityClient/#/ubs
Sign in as admin

**Steps to reproduce**
1. Click the 'UBS-admin' button in pop-up window
2. Click the button "Замовлення"
3. Click on the button "Фільтри"
4. Choose the filter "Статус замовлення"

**Actual result**
The status "Оплачено" is absent for "Статус замовлення" . The order of some statuses doesn't coincide with the mock-up.  
<img width="314" alt="Screenshot 2022-05-31 at 17 01 46" src="https://user-images.githubusercontent.com/103331829/171194231-ab8da501-204f-49a3-91e6-4691f7e3ac1a.png">

**Expected result**
The status "Оплачено" is present for "Статус замовлення". The order of statuses is like on the mock-up: 
<img width="208" alt="Screenshot 2022-05-31 at 17 12 56" src="https://user-images.githubusercontent.com/103331829/171194413-05a0d061-440d-4218-81b6-864365e41226.png">

**User story and test case links**
User story #3300 
Mock-up: https://www.figma.com/file/JvDAu4MHnh1Vxc5FaokyiA/ITA-UBS-styles?node-id=18582%3A52286

**Comment by GitVladyslav** [comment]
The order of the statuses does not match the mock-up.
![Фільтри убс замовлення](https://user-images.githubusercontent.com/112887882/190924068-53959c83-d278-4832-8e2c-65f65ea26452.png)

**Comment by natalijawirt** [comment]
This bug is  not valid. 
According to US https://github.com/ita-social-projects/GreenCity/issues/3300 
order status in  Статус замовлення are discribed in US https://github.com/ita-social-projects/GreenCity/issues/2901
and status Оплачено was deleted
![image](https://user-images.githubusercontent.com/49556759/195327649-138cf18e-25fa-44b7-860c-6c7cc4351ee0.png)

**Comment by NataliaVirt** [comment]
This bug is not valid 
According to US https://github.com/ita-social-projects/GreenCity/issues/3300
Order statuses in  "Cтатус замовлення" are described in https://github.com/ita-social-projects/GreenCity/issues/2901
And status "Оплачено"  was deleted
![image](https://user-images.githubusercontent.com/112310945/195329500-91e94843-63f6-4acc-813d-90f9a1beb3c6.png)

Please, remove this status in filters -> Статус замовлення
