### ISSUE TITLE
The incorrect text pops up is shown after the user is registered

### ISSUE THREAD

**Issue by Talichka** [ita-social-projects/GreenCity#493]
**Steps to reproduce:**

1. Go to the https://ita-social-projects.github.io/GreenCityClient/#/auth/sign-up
2. Fill in with the valid data fields: 'First Name', 'Last Name', 'Email', 'Password', 'Password Confirm' 
3. Click the 'Sign-up' button
4. Look at the pops up text
**Expected Result:**
The following text pops up is - 'You successfully registered on this site. Please verify your email address in email box'
**Actual Result:**
'You have successfully registered on the site. Please confirm your email address in the email box' text pops up is shown
**Environment:** Chrome Версія 80.0.3987.122 (Розробка) (64-розрядна версія) Windows7 Ultimat

**Comment by Talichka** [comment]
![registration](https://user-images.githubusercontent.com/40841118/75925076-b7219180-5e70-11ea-9758-0e609619224c.png)

**Comment by lenadgit** [comment]
All texts were given for us by experts.
Your example of the sentence is not correct:
"You successfully registered on this site. Please verify your email address in email box'"
1) "verify" - is not correct in this case, because user must confirm the registration (not only verify)
2) phrase "You have successfully registered" - is correct because a Present Perfect Tense must be used (https://grammarway.com/ua/present-perfect)  instead of Past Indefinite (https://grammarway.com/ua/past-simple)
3) "in the email box" - is correct, because (a\the) must be before the noun (https://grammarway.com/ua/article)
