### ISSUE TITLE
[Admin Cabinet] The dates on the 'Статус замовлення" column are not sorted in the “Я”-”A” order after clicking on the arrow icon

### ISSUE THREAD

**Issue by nata000** [ita-social-projects/GreenCity#5102]
Environment: macOS Big Sur 11.3,Google Chrome 105.0.5195.125
Reproducible:always
Build found: 29.01.2023

Preconditions

User is logged in as administrator.
User navigated to the Orders tab
There is at least two order on the 'Order' table with different  statuses

Steps to reproduce

1. Click on the arrow icon on the 'Статус замовлення' column
2. Pay attention on the statuses sorting

Actual result
The statuses of order are not sorted in the  “Я”-”A” format on the 'Статус замовлення" column after clicking on the arrow icon
Expected result
The statuses of order are sorted in the  “Я”-”A” format and icon points upwards  on the 'Статус замовлення" column after clicking on the arrow icon

User story and test case links
E.g.: "User story #2537

Labels to be added
"Bug", Priority ("pri: "), Severity ("severity:"), Type ("UI, "Functional"), "API" (for back-end bugs).
<img width="705" alt="Знімок екрана 2023-01-29 о 16 40 50" src="https://user-images.githubusercontent.com/112875002/215333928-f9192bf0-6d30-4c73-85e5-f28ff03e1140.png">

**Comment by DanaIuich** [comment]
The statuses of order are not sorted in the “Я”-”A” format on the 'Статус замовлення" column after clicking on the arrow icon

**Comment by Maxv1z** [comment]
Sorting works only in English localization, since property used for sorting - `orderStatus`, comes in English only. So when we make a request to fetch data in asc or desc order, system does it accordingly to English alphabet, not depending on the language chosen. 
The way to resolve the bug is to add `orderStatus` in both languages in the endpoint `
https://greencity-ubs.greencity.social/ubs/management/bigOrderTable`, so the frontend can get sorted tables depending on the user's language.
![Без імені](https://github.com/ita-social-projects/GreenCity/assets/122612827/a7cc38bd-ca86-4073-a992-cea89b9d9812)

**Comment by ViktoriyaRyazhska** [comment]
Dublicate #5527
