### ISSUE TITLE
[UBS-User.Edit Profile] Checkbox "Зробити адресою за замовчуванням" absent on profile edit page 

### ISSUE THREAD

**Issue by patselyuk** [ita-social-projects/GreenCity#5354]
**Environment:** macOS 12.6.2 (21G320), browser Chrome 110.0.5481.177 (Official Build)
**Reproducible:** always
**Build found:** 28.02.23

**Preconditions**

1. User is logged in as User https://www.testgreencity.ga/#/ubs
2. User is on the UBS-user (in the top right clicking username)
3. User is on the 'User Data' tab
4. More than one address is added

**Steps to reproduce**
1. Click on 'Edit data' button

**Actual result**
https://www.screencast.com/t/gNescghiqkD

**Expected result**
https://www.screencast.com/t/RlbJVRmhq

**User story and test case links**
E.g.: "User story #3811 
[Test case](https://jira.softserve.academy/browse/GC-2828)"

**Labels to be added**
"Bug", Priority ("pri: "), Severity ("severity:"), Type ("UI, "Functional"), "API" (for back-end bugs).

**Comment by Olena-Kharkova** [comment]
The bug is not fixed on PROD
https://user-images.githubusercontent.com/110603507/229279409-1f2698e9-cdb3-4cbb-b7ba-71b1c0a1e717.mp4

Incorrect title of UI element on TEST: there is 'Зробіть цe адресою за умовчанням' instead of 'Зробити адресою за замовчуванням' -> US https://github.com/ita-social-projects/GreenCity/issues/3811

![2ZSNxkDw6M](https://user-images.githubusercontent.com/110603507/229279602-649f5f5e-3107-4065-a2cd-6aec3b414ab6.png)

**Comment by DanaIuich** [comment]
Bug is fixed
