### ISSUE TITLE
[UBS Tariffs Page. Add new service "Послуга"] Digits and special characters must be allowed in Найменування послуги and Name of the service fields of the "Додати послгу" pop-up window

### ISSUE THREAD

**Issue by BohdanaYuzkiv** [ita-social-projects/GreenCity#5783]
Environment: Windows 10, Chroome Version 111.0.5563.65
Reproducible: always
Build found: 13.05.2023

**Preconditions**

1. The user should be authorized as Admin
2. Main UBS menu -> page 'Тарифи' should be opened
3. Click on the tariff card available from the list 

**Steps to reproduce**

1. Click on "Add service"/"Додати послугу" button
2. Pay attention to the 'Name of the tariff' field
3. Pay attention to the 'Найменування послуги' field

**Actual result**
only letters are allowed

**Expected result**
Letters, digits and special characters are allowed. From minimum 1 to maximum 30 characters are allowed.

**User story and test case links**
User story #4429

**Labels to be added**
"Bug", Priority ("pri: "), Severity ("severity:"), Type ("UI, "Functional"), "API" (for back-end bugs).

**Comment by RudnevaOlena** [comment]
The bug is still displayed, namely when numbers are at the start of "Найменування послуги" and when the special characters (* : ; ? " {} [] () % . !) are entered in the field "Найменування послуги".
<img width="595" alt="Screenshot 2023-07-28 at 12 54 46" src="https://github.com/ita-social-projects/GreenCity/assets/128076020/868adf1a-86e7-4558-ad32-355c2446fda9">
<img width="591" alt="Screenshot 2023-07-28 at 12 54 00" src="https://github.com/ita-social-projects/GreenCity/assets/128076020/66337b2f-7eef-4821-8962-01bdb7993781">

**Comment by Daria811** [comment]
Digits and special characters shouldn't be allowed to enter the 'Найменування послуги' and 'Name of the tariff' fields.
But it must be allowed, according to the [link](https://github.com/ita-social-projects/GreenCity/issues/4429).
![image](https://github.com/ita-social-projects/GreenCity/assets/165039674/d92b1c7d-db7f-4508-b1be-d1cc071301c4)
