### ISSUE TITLE
[UBS_Prod. Tariffs User] User gets 400 when trying to save changes (address) into personal cabinet

### ISSUE THREAD

**Issue by BohdanaYuzkiv** [ita-social-projects/GreenCity#5912]
Environment: Windows 10, Chrome Version 108.0.5359.99
Reproducible: always
Build found: 05.06.23

**Preconditions**

1. Go to the https://www.pick-up.city/
2. User should be authorized as User

**Steps to reproduce**
1. Go to 'User data' page
2. Click on 'Edit data' button
3. Make some changes in the previously filled info (e.g. change house number)

**Actual result**
 Error message appears after clicking on the 'Save' button, page is loading

![change](https://github.com/ita-social-projects/GreenCity/assets/109086383/8266408f-b204-4f90-b10d-d779b048533b)

![06 06 2023_20 53 06_REC](https://github.com/ita-social-projects/GreenCity/assets/109086383/cb59a77b-2c16-4484-a355-97e57b743ac4)

![06 06 2023_20 53 49_REC](https://github.com/ita-social-projects/GreenCity/assets/109086383/08682d65-3467-4485-8db1-8b4c55ba9d05)

**Expected result**
Changes are saved after clicking on the 'Save' button

**User story and test case links**
E.g.: "User story #100
[Test case](https://jira.softserve.academy/browse/100)"

**Labels to be added**
"Bug", Priority ("pri: "), Severity ("severity:"), Type ("UI, "Functional"), "API" (for back-end bugs).

**Comment by ABbondar** [comment]
retest please

**Comment by RudnevaOlena** [comment]
https://github.com/ABbondar Hello, after retesting the bug is still there, namely when we change the house number and press the "save changes" button, it first shows a message that the changes have been saved, and then immediately an error message, while the changes are immediately displayed, but after updating or clicking on the profile tab of left menu - previous data are displayed (before changes) 
![BB73A57D-14CC-4BF3-9D26-FDA8E9853E12](https://github.com/ita-social-projects/GreenCity/assets/128076020/e1c4027f-5945-43de-bbc3-f022e4c7469d)
![A62E79DD-E2E7-4240-A699-8A770E1D7A09](https://github.com/ita-social-projects/GreenCity/assets/128076020/940bb1c3-6bbd-4ac0-b4dd-2245c88097e1)

**Comment by RudnevaOlena** [comment]
@ABbondar , I have tested API for this bug and it doesn't work correctly 
![Image 26 06 2023 at 18 14](https://github.com/ita-social-projects/GreenCity/assets/128076020/8c24ddec-253a-4709-9dff-201cee414c0d)

**Comment by ABbondar** [comment]
@RudnevaOlena Hello, changing the house numbers in user profile works correctly:

https://github.com/ita-social-projects/GreenCity/assets/53192419/669fb215-d008-49c2-b3fd-34febd72490e

Updating the address in order details also works correctly, we must to choose house numbers from drop down menu on front-end side:

https://github.com/ita-social-projects/GreenCity/assets/53192419/2ec5dbdc-cb1f-4e43-a8ab-8b87cfe8cdba

**Comment by RudnevaOlena** [comment]
Retesting on Chrome Version 114.0.5735.198 (Official Build) (arm64) and Safari Version 16.5.2 (18615.2.9.11.10), for the Kyiv location, was successful.
