### ISSUE TITLE
[User's personal cabinet] Doesn't edit the employee name on the personal cabinet employee

### ISSUE THREAD

**Issue by HalynaChornevych** [ita-social-projects/GreenCity#6142]
Environment: Windows 10 Pro 20H2
Google Chrome 113.0.5672.93
Reproducible: always
Build found: 08.08.2023
Preconditions

1. The user should be logged in https://www.greencity.social/#/greenCity as a Super Admin
2. In the tab "Employees" the employee added

Steps to reproduce

1. Click on the 'Employee' tab
2. In the tab 'Employee' choose the Employee
3. In pop-up window click on 'Edit employee data'
4. Enter the new data  (e.g. in the field Last name)
5. Employee logs in to their profile
6. Click on the icon in the upper right corner
7. In pop-up window click on "Settings"
8. Pay attention to the 'Name field'

Actual result
The 'Name field' displays the previous data 'First name' and 'Last name'  employee

Expected result
The 'Name field' displays the new data 'First name' and 'Last name'  employee

User story https://github.com/ita-social-projects/GreenCity/issues/4617, https://github.com/ita-social-projects/GreenCity/issues/3811

"Bug", Priority ("Medium"), Severity ("Major"), Type ("UI"), "API" (for back-end bugs)
![Screenshot_2](https://github.com/ita-social-projects/GreenCity/assets/131760121/b43f9476-daa8-4cbe-8eda-2d469a2cc49c)
![Screenshot_3](https://github.com/ita-social-projects/GreenCity/assets/131760121/30c31aef-cf25-4197-9943-9321ff43358d)
![Screenshot_4](https://github.com/ita-social-projects/GreenCity/assets/131760121/17be6dc3-4451-4d5d-8465-7e38f9a6b4ec)

**Comment by ospodaryk** [comment]
Bug Retesting needed.
This error is on front-end  side
Our site is connected to 2 different databases and the settings button (which is no longer on the site) leads to different data than those on the ubs page
<img width="267" alt="image" src="https://github.com/ita-social-projects/GreenCity/assets/82940222/3b618432-6a69-4e9f-b940-2528e278bd4d">
In order to go to edit the ubs data, you need to go here 
<img width="689" alt="image" src="https://github.com/ita-social-projects/GreenCity/assets/82940222/d5dcb34d-9fdb-414f-9655-8327aa81cdeb">

**Comment by DanaIuich** [comment]
The functionality has been removed
