### ISSUE TITLE
[Change request to #3193] <Create event>

### ISSUE THREAD

**Issue by dklakovych** [ita-social-projects/GreenCity#6359]
**Description of a Change request:**
Minor changes in functionality.

**Reason for Change:**
To clarify some misunderstanding moments.

**Mockups**:
1 день 
https://www.figma.com/file/092AhCGadc1Hq8nAysxmYB/ITA-Greencity-%D0%A3%D0%91%D0%A1?type=design&node-id=50699-47722&mode=design
2 дня 
https://www.figma.com/file/092AhCGadc1Hq8nAysxmYB/ITA-Greencity-%D0%A3%D0%91%D0%A1?type=design&node-id=50699-55581&mode=design

**Acceptance Criteria**
_According to the original order_

**7.1** Only fields with 'Start Time' and 'End Time' should be disabled when the user checks off the “All day” checkbox, but the Date field should stay active.

**19.1** _Add_: When the picture format isn’t correct, error message like this should appear: “Incorrect picture format. Use files in JPG or PNG format instead”, and highlight it in red colour.

**Impact of Change**
[#3193](https://github.com/ita-social-projects/GreenCity/issues/3193)

**Labels to be added**
[change request: adjustment]

**Epic**: [#3194](https://github.com/ita-social-projects/GreenCity/issues/3194)

**Comment by Priadkohrystyna** [comment]
In case the picture format isn’t correct, error message  "Incorrect image type" is appear instead of message “Incorrect picture format. Use files in JPG or PNG format instead”
![Знімок екрана 2023-09-27 140716](https://github.com/ita-social-projects/GreenCity/assets/106020174/d3064427-1d89-4843-8b95-fd91bf76123c)
