### ISSUE TITLE
[Forgot password]: 'Sign-in with Google' button instead of 'Sign-up with Google' button.

### ISSUE THREAD

**Issue by MariaKorniavka** [ita-social-projects/GreenCity#644]
**Environment:** macOS Catalina 10.15.4, Google Chrome 81.0.4044.122 (64-bit), Safari 13.1, Firefox 75.0 (64-bit)
**Reproducible:** always
**Build found:** commit 7439e88

**Preconditions:**
Go to GreenCity url: https://ita-social-projects.github.io/GreenCityClient/#/welcome;

**Steps to reproduce:**
1. Click on the 'Sign in' button in the top right part of the window.
2. Click on 'Forgot password?' link.

**Actual result:**
'Sign-in with Google' button is present at the 'Forgot password' pop-up.

<img width="1010" alt="Incorrect button" src="https://user-images.githubusercontent.com/64583209/81218536-027a2c80-8fe7-11ea-9576-20f9ba0224e7.png">

**Expected result:**
'Sign-up with Google' button should be present at the 'Forgot password' pop-up.

<img width="609" alt="Figma" src="https://user-images.githubusercontent.com/64583209/81218557-0ad26780-8fe7-11ea-8333-52eb62012bdf.png">

User story: #472

**Comment by nvolodymyr** [comment]
fix

**Comment by NazariyPylypchuk** [comment]
The bug is opened due to bug verification 
a bug is not fixed yet 
**Environment: Safari 13.1**
_Actual result:_ 
Button 'Надіслати посилання для входу' wrong alignment and color
Button 'Увійти через гугл'
_Expected result:_
Button 'Надіслати посилання для входу' background color must be #13AA57 and size of the button 368x48.
Button 'Зареєструватись через гугл' must be present
<img width="911" alt="Screenshot 2020-07-22 at 13 41 10" src="https://user-images.githubusercontent.com/34487672/88168775-91c8d080-cc23-11ea-96d0-db2744a98f07.png">
**Environment: Google Chrome 81.0.4044.122 (64-bit), Firefox 75.0 (64-bit)**
_Actual result:_ 
Wrong color of the button 'Надіслати посилання для входу'
_Expected result:_ button background color must be #13AA57
<img width="814" alt="Screenshot 2020-07-22 at 14 03 31" src="https://user-images.githubusercontent.com/34487672/88169127-32b78b80-cc24-11ea-9889-5fe0222f5c71.png">

**Comment by stasgoodman** [comment]
Should be "Увійти через Goodle" 
Desided on meeting by @ViktoriyaRyazhska
