### ISSUE TITLE
[Post/News] API  An authorized User can likes its own comments and replies

### ISSUE THREAD

**Issue by VlasenkoYuliia** [ita-social-projects/GreenCity#6586]
Environment:
macOS Sonoma Version 14.0
Postman

Reproducible: always.
Build found:
19.10.23

Preconditions
A User is logged in;
the token is added.

**Steps to reproduce**
eco-news-comment-controller
Post /econews/comments/like

**Actual result**
An authorized User likes its own comments and replies.

https://github.com/ita-social-projects/GreenCity/assets/138223368/1e0377de-1ad0-4510-a255-46988ed881d1

**Expected result**
An authorized User can like just the other user’s comments/replies.

**Postconditions**

**User story and test case links**
E.g.: "User story #766 
[Test case]()"

**Labels to be added**
"Bug", Priority ("Low"), Severity ("Trivial"), Type ("Functional"), "API" (for back-end bugs).

**Comment by ryhaldenys** [comment]
This bug is not reproduced

**Comment by SvitlanaRadkevych** [comment]
The bug has been fixed in swager. However, it is not possible to leave a like for anyone on the site. Even the admin does not have rights.
![Like](https://github.com/ita-social-projects/GreenCity/assets/165490180/7c5926da-966c-47ea-8b5c-c7923bbda57d)

https://github.com/ita-social-projects/GreenCity/assets/165490180/ab1ff779-ccaa-41fd-8508-f72acf671542
