### ISSUE TITLE
[Sign-in] When user moved to 'Sign-in' window, appeared scroll bar.

### ISSUE THREAD

**Issue by Phobos13bdrive** [ita-social-projects/GreenCity#6793]
**Environment:** Firefox 121.0 (64-bit.
**Reproducible:** always.
**Build found:** last commit from https://github.com/ita-social-projects/GreenCityClient/tree/dev
E.g. "commit 147fa44"

**Preconditions**
Moved to https://www.greencity.social/#/greenCity

**Steps to reproduce**
1. Click on 'Sign-in' bttn.

**Actual result**
When user moved to 'Sign-in' window, appeared scroll bar.

**Expected result**
Scroll bar must be appeared only when user make scalking-up.

**Postconditions**
A clear and concise description of actions to be done after bug reproducing. E.g.:
"Delete created item from database using SQL query:
DELETE FROM table1
WHERE id=<item1_id>;"

**Labels to be added**
"Bug", Priority ("pri: "), Severity ("severity:"), Type ("UI, "Functional"), "API" (for back-end bugs).

**Comment by dijulya** [comment]
The bug is not fixed:
When an user navigates to the 'Sign in' window, a scroll bar still appears
![Actual result](https://github.com/ita-social-projects/GreenCity/assets/61908979/8155be17-d0b8-4691-9394-81fec3a79622)

**Comment by dijulya** [comment]
The bug keeps reproduce on Mozilla 124.0.2 (64-bit)
![6793_1](https://github.com/ita-social-projects/GreenCity/assets/61908979/42b0c71b-b1ae-4fdd-9320-f9bdc7d30d09)

**Comment by Roksana77** [comment]
The bug is reproduced on Chrome 127.0.6533.100 (64-bit)


![scroll bar](https://github.com/user-attachments/assets/2b0aa553-afd7-44de-928e-bd1aed159557)

**Comment by bstarchuk** [comment]
Added a fix to the login and registration modal so that the scrollbar is displayed only on a small screen when necessary
Pull Request: https://github.com/ita-social-projects/GreenCityClient/pull/3272

### Result:
Normal size of window:
![Image](https://github.com/user-attachments/assets/157767ba-79ea-464b-a111-fdbb5c6756c0)
Small size of window:
![Image](https://github.com/user-attachments/assets/1a3404e6-acd8-426d-b06a-7820f1306ed4)
