### ISSUE TITLE
 [API/Client Controller/Pick-up City/Orders] When we enter our order ID, the status 404 is displayed

### ISSUE THREAD

**Issue by Nastya1403** [ita-social-projects/GreenCity#7138]
**Environment:** Windows 11 Home, Google Chrome 124.0.6367.119 (Official Build) (64-bit)
**Reproducible:** always
**Build found:** 14.05.2024

**Preconditions**
1. The user is logged in at https://www.pick-up.city/#/ubs
2. The user has one created order
3. Postman is opened and the token is gotten.

**Steps to reproduce**
1. Create a request with method - GET to URL https://greencity-ubs.pick-up.city/ubs/client/get-data-for-order-surcharge/{id}
where id is from precondition №2
3. Send the request

**Actual result**
The status code 404 with an error message "Employee with current id doesn't exist: " is displayed
![image](https://github.com/ita-social-projects/GreenCity/assets/61518116/f68758ff-a5a0-4ee4-ac9e-b9892f27fbb5)

**Expected result**
The status code 200 and information about order are displayed

**User story and test case links**
[Swagger](https://greencity-ubs.pick-up.city/swagger-ui.html#/)

**Comment by HelenSotnik** [comment]
<img width="1470" alt="Screenshot 2024-05-20 at 21 09 23" src="https://github.com/ita-social-projects/GreenCity/assets/63450632/4cb3c6ad-7652-42ca-a168-5d1f79815508">
Current endpoint is applicable not for user to see info about order, but for Employee. But there will be this error anyway due to parsing employee email, which is passed instead as uuid. I could be fixed.But it is not used, so will be deleted.
