### ISSUE TITLE
[My habits] Incorrect avatars are displayed on the collective habit card

### ISSUE THREAD

**Issue by OlhaNechaieva** [ita-social-projects/GreenCity#7465]
Environment:
Windows 11 Pro Version 23H2, x64
Google Chrome Version 128.0.6613.137 (Official Build) (64-bit)
Firefox 127.0 (64-bit) 

Reproducible: always

Preconditions
The user has at least one collective habit in progress.

Steps to reproduce

1. Go to the https://www.greencity.social/#/greenCity website
2. Log in
3. Click the 'My Space' tab.

Actual result:
Show avatars of a friend that track the same habit as user.
![Image](https://github.com/user-attachments/assets/914b0ea4-25cd-4c30-b104-9394085bcc32)

Expected result:
Shows avatars of friends who are invited to track the habit together.

User story: https://github.com/ita-social-projects/GreenCity/issues/988

**Comment by kovalsofiia1** [comment]
Hi @borntoshine1 , the user should be able to see avatars of users who already track this habit, if the user was only invited, but did not accept the invite he  shouldn`t be there

**Comment by OlhaNechaieva** [comment]
Hi @kovalsofiia1, after clarifying with the product owner, I received an answer: the avatars of the friends with whom you track your habit should be displayed, as specified in the user story.

**Comment by bzhn** [comment]
Hi @borntoshine1,

The business logic of showing users' avatars is managed on the back-end. List of the avatars for habit card is returned from the following endpoint

https://greencity.greencity.cx.ua/habit/539/friends/profile-pictures

where 539 is habit ID.

[Swagger](https://greencity.greencity.cx.ua/swagger-ui/index.html#/habit-controller/getFriendsAssignedToHabitProfilePictures)

This means that the issue is related to back-end and not front-end, so more labels should be added to the issue.
