### ISSUE TITLE
[Display news] Incorrect resolutions breakpoints and containers size in the 'List view'

### ISSUE THREAD

**Issue by rsyvulko** [ita-social-projects/GreenCity#828]
**Environment:** Windows 10 x64, Mozilla Firefox 76.0 (64-bit)
**Reproducable:** always
**Build found:** commit c21fa11

**Steps to reproduce**
1. Go to GreenCity https://ita-social-projects.github.io/GreenCityClient/#/welcome
2. Click on 'List view' button in top right part of the window.
3. Set window width to **1200px** and verify News item's container and Image size using browser Devtools.
4. Set window width to **1199px** and verify News item's container and Image size using browser Devtools.
5. Set window width to **992px** and verify News item's container and Image size using browser Devtools.
6. Set window width to **991px** and verify News item's container and Image size using browser Devtools.
7. Set window width to **769px** and verify News item's container and Image size using browser Devtools.
8. Set window width to **768px** and verify News item's container and Image size using browser Devtools.
9. Set window width to **767px** and verify News item's container and Image size using browser Devtools.
10. Set window width to **577px** and verify News item's container and Image size using browser Devtools.
11. Set window width to **576px** and verify News item's container and Image size using browser Devtools.
12. Set window width to **575px** and verify News item's container and Image size using browser Devtools.

**Actual result**
1. News item's container size at **1200px** is **1110x238px**. Image size is 359x214px.
2. News item's container size at **1199px-992px** is **930x238px**. Image size is 359x214px.
3. News item's container size at **991-769px** is **690x238px**. Image size is 359x214px.
4. News item's container size at **768px** is **690x238px**. Image size is 214x214px.
5. News item's container size at **767-577px** is **510x238px**. Image size is 214x214px.
6. News item's container size at **576px** is **510x238px**. Image is absent.
7. News item's container size at **575px** is **545x238px**. Image is absent.
![List 1200](https://user-images.githubusercontent.com/64583544/83461673-ffe9e600-a471-11ea-999f-c26d847e33b1.png)
![List 1199](https://user-images.githubusercontent.com/64583544/83461697-0d06d500-a472-11ea-8e66-5c6269a4b367.png)
![List 991](https://user-images.githubusercontent.com/64583544/83461715-14c67980-a472-11ea-8507-f17fcbe200d0.png)
![List 768](https://user-images.githubusercontent.com/64583544/83461717-17c16a00-a472-11ea-8762-df414e65db44.png)
![List 767](https://user-images.githubusercontent.com/64583544/83461723-1b54f100-a472-11ea-9d45-5f602924cab9.png)
![List 576](https://user-images.githubusercontent.com/64583544/83461735-20b23b80-a472-11ea-81b0-e2cf7e278746.png)
![List 575](https://user-images.githubusercontent.com/64583544/83461761-3293de80-a472-11ea-9297-d6336edf7ab5.png)

**Expected result**
1. News item's container size at **1200px** is **1140x246px**. Image size is 359x314,71px.
2. News item's container size at **1199px-992px** is **960x246px**. Image size is 359x314,71px. 
3-4. News item's container size at **991-768px** is **740x246px**. Image size is 214x314,71px.
5-6. News item's container size at **767-576px** is **scalable**. Image is absent.
7 . News are displayed in the Gallery view at **575px** and less resolution.
![List 1200+](https://user-images.githubusercontent.com/64583544/83461767-358ecf00-a472-11ea-88cc-cf428f460c7b.png)
![List 992+](https://user-images.githubusercontent.com/64583544/83461795-47707200-a472-11ea-8117-58693b114956.png)
![List 768+](https://user-images.githubusercontent.com/64583544/83461808-522b0700-a472-11ea-941c-3dd0fd4f8797.png)
![List 576+](https://user-images.githubusercontent.com/64583544/83461800-4b03f900-a472-11ea-95db-1985a190fff3.png)

User story #460 
[Test case](https://jira.softserve.academy/browse/GC-720)

**Comment by vitaliipolitylo** [comment]
### **Not a bug.**
Design resolution and application resolution are identical.

![NotABug](https://user-images.githubusercontent.com/39058788/93913301-8ec68b00-fd0d-11ea-99bf-c9a74a8e2c64.PNG)
![NotABug1](https://user-images.githubusercontent.com/39058788/93913306-90904e80-fd0d-11ea-8594-c7d334a421cf.PNG)

**Comment by natalinapr** [comment]
**Actual result:**
768px: container width=742
![Eco news](https://user-images.githubusercontent.com/62031226/98949360-4868fd80-2500-11eb-85eb-47354050ec6e.png)


**Expected result:** 
768px: container width=740
![image](https://user-images.githubusercontent.com/62031226/98949401-561e8300-2500-11eb-9477-ba8fdaf3a9f6.png)

**Comment by vitaliipolitylo** [comment]
### **Everything is made according to the mockup**

### **1440:**
**Mockup:**
![image](https://user-images.githubusercontent.com/39058788/100871504-11f02400-34a9-11eb-9aa2-2706797ba86e.png)
![image](https://user-images.githubusercontent.com/39058788/100872022-d73abb80-34a9-11eb-81ee-2eb5c88307e5.png)

**Actual result:**
![image](https://user-images.githubusercontent.com/39058788/100871660-4cf25780-34a9-11eb-8506-94861d8915a1.png)
![image](https://user-images.githubusercontent.com/39058788/100872106-f9ccd480-34a9-11eb-89ba-f8b70598b492.png)

> ------------------------------

### **1024:**
**Mockup:**
![image](https://user-images.githubusercontent.com/39058788/100872234-2b45a000-34aa-11eb-8e6c-115b7b5900a6.png)
![image](https://user-images.githubusercontent.com/39058788/100872270-3a2c5280-34aa-11eb-9fe0-ab8759a32c3c.png)

**Actual result:**
![image](https://user-images.githubusercontent.com/39058788/100872330-53cd9a00-34aa-11eb-9edd-abc722841786.png)
![image](https://user-images.githubusercontent.com/39058788/100872374-634ce300-34aa-11eb-9ccf-fa9eb3b34d80.png)

> ------------------------------

### **768:**
**Mockup:**
![image](https://user-images.githubusercontent.com/39058788/100872551-a3ac6100-34aa-11eb-9f25-87cd276680d2.png)
![image](https://user-images.githubusercontent.com/39058788/100872608-b9ba2180-34aa-11eb-918b-577332e39fb9.png)
(Here width in mockup is bigger because it counts hidden part of image, but visible part has same width with actual result)

**Actual result:**
![image](https://user-images.githubusercontent.com/39058788/100872776-030a7100-34ab-11eb-9d64-e521209d6b9b.png)
![image](https://user-images.githubusercontent.com/39058788/100872818-13bae700-34ab-11eb-9d62-c6f6c91f80f6.png)

> ------------------------------

### **576:**
**Mockup:**
![image](https://user-images.githubusercontent.com/39058788/100873006-5bda0980-34ab-11eb-8448-1f1a76c6f197.png)

**Actual result:**
![image](https://user-images.githubusercontent.com/39058788/100873076-71e7ca00-34ab-11eb-9e90-f97e648421a0.png)

> ------------------------------

### **Conclusion:**
It is not actually a bug. Everything is made according to the mockup.

**Comment by VasylynaYaremkiv** [comment]
there is an  mistake on the mockup, becausethe height of the container changes not in proportion to the change in the width of the container, there will be changes in the mockup, it is agreed with the designers, so when expanding 1024 the height of the container should not be 166 but 194-195 pixels

**Comment by Nazar-Blashchak** [comment]
According to new (https://www.figma.com/file/092AhCGadc1Hq8nAysxmYB/ITA-Greencity-УБС?node-id=12671%3A6458) mock-ups bug is fixed.
