### ISSUE TITLE
[Display news] Buttons that change list view or gallery view are absent when screen resolution is 576 px width

### ISSUE THREAD

**Issue by BohdanPrysiazhnyi** [ita-social-projects/GreenCity#999]
Environment: Windows 10 home 64bit, Google Chrome 84.0.4147.89
Windows 10 Pro, Mozilla Firefox 82.0.3 (64-біт)
Reproducible: always

Steps to reproduce:

1. Go to GreenCity https://ita-social-projects.github.io/GreenCityClient/#/news
2. Using dev tools change screen resolution width for the current page to 576px

Actual result:
Only list view is present.
![absent galery-list view](https://user-images.githubusercontent.com/68583636/88485030-a71f6100-cf7b-11ea-8894-10783babd464.jpg)

Expected result:

![present](https://user-images.githubusercontent.com/68583636/88485084-09786180-cf7c-11ea-816d-482b590dfe48.jpg)

User story #459 [https://github.com/ita-social-projects/GreenCity/issues/459](url)
Test case on JIRA [674](https://jira.softserve.academy/browse/GC-674)

**Comment by Volodymyr-Danyliv** [comment]
The button displayed not fully:
![image](https://user-images.githubusercontent.com/29017153/90214145-422f8c00-de00-11ea-8a8c-c495c63fa065.png)

**Comment by oprotyniak** [comment]
The bug is still present in Mozilla. In Chrome when in "Gallery View" mode the control of "Gallery view" is partially visible.

**Environment:** Windows 10 Pro, Mozilla Firefox 82.0.3 (64-біт)
**Reproducible:** always
**Build found:** 20.11.2020

**Preconditions**
1. https://ita-social-projects.github.io/GreenCityClient/ is opened.
2. News items are created in the DB and are displayed as first news item in the list view. Use queries:
INSERT INTO eco_news
(ID, title, text, author_id, creation_date)
VALUES (725, 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim ven',
'Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure d',
857, '<current date and time in format e.g. "2020-05-17 10:00:00.000000">');

INSERT INTO eco_news_tags
(eco_news_id, tags_id)
VALUES (725, 1), (725, 3);

**Steps to reproduce**
1. Go to GreenCity https://ita-social-projects.github.io/GreenCityClient/#/welcome
2. Click on 'Eco news' link in the header.
3. Set browser window width to 576px.
4. Pay attention to right upper corner of first news.

**Actual result**
- No controls for 'Gallery view' and 'List view' are shown.
![image](https://user-images.githubusercontent.com/73852063/99739093-a1bec700-2ad4-11eb-8dda-ed1de74a4df9.png)



**Expected result**
- Controls for 'Gallery view' and 'List view' are shown.
![image](https://user-images.githubusercontent.com/73852063/99740670-17786200-2ad8-11eb-9cc1-c80c00c4771a.png)


**Postconditions**
DELETE FROM eco_news_tags
WHERE eco_news_id = 725;

DELETE FROM eco_news
WHERE id = 725;

**User story and test case links**
User story #460
[Test case](https://jira.softserve.academy/browse/GC-725)

**Comment by JimHolman1199** [comment]
looks fine on my end 
<img width="1184" alt="Screenshot 2020-12-15 at 21 44 24" src="https://user-images.githubusercontent.com/46226026/102264833-d892cc00-3f1e-11eb-87f0-322796fd1aca.png">

**Comment by oprotyniak** [comment]
The bug was fixed in Chrome, but still exists in Mozilla
![image](https://user-images.githubusercontent.com/73852063/103490059-e3f05d80-4e21-11eb-8753-85c0c41e939d.png)
